account-config:
  accounts:
    -
      tvtimeUser: ${TVTIME_USER}
      tvtimePassword: ${TVTIME_PASSWORD}
      plexUsers: ${PLEX_USERS}
      plexShowsExclude: ${PLEX_SHOWS_EXCLUDE:}
      plexShowsInclude: ${PLEX_SHOWS_INCLUDE:}
logging:
  level:
    com:
      zggis: ${LOGGING_LEVEL:INFO}
  file:
    name: ${logfile.dir}/plex-tvtime.log
logfile:
  dir: /logs
track-movies: ${TRACK_MOVIES:false}
mark-previous-episodes: ${MARK_PREVIOUS_EPISODES:false}
mark-rewatch-episodes: ${MARK_REWATCH_EPISODES:false}
discord:
  webhook-url: ${DISCORD_WEBHOOK_URL:}
  notify-on-startup: ${DISCORD_NOTIFY_ON_STARTUP:true}
  host-url: ${DISCORD_HOST_URL:}
server:
  port: ${SERVER_PORT:8080}
