version: '3.9'
services:
  plex-tvtime:
    image: zggis/plex-tvtime:latest
    ports:
      - '8080:8080'
    environment:
      - TVTIME_USER=${TVTIME_USER}
      - TVTIME_PASSWORD=${TVTIME_PASSWORD}
      - PLEX_USERS=${PLEX_USERS}
      - TRACK_MOVIES=${TRACK_MOVIES:-false}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
      - DISCORD_HOST_URL=${DISCORD_HOST_URL:-}
      - DISCORD_NOTIFY_ON_STARTUP=${DISCORD_NOTIFY_ON_STARTUP:-true}
    volumes:
      - ./logs:/logs
      - ./config:/config
    restart: unless-stopped

